version: '3.9'

services:
  nuxt-dev.test:
    build:
      context: .
      dockerfile: node.dockerfile
    working_dir: /srv/web
    volumes:
      - ./src:/srv/web
      - ${HOME}/.npm:${HOME}/.npm
      - ${HOME}/.npm-global:${HOME}/.npm-global
    command: yarn dev
    ports:
      - "3000:3000"

  nuxt-prod.test:
    build:
      context: .
      dockerfile: node.dockerfile
    working_dir: /srv/web
    volumes:
      - ./src:/srv/web
      - ${HOME}/.npm:${HOME}/.npm
      - ${HOME}/.npm-global:${HOME}/.npm-global
    command: [sh, -c, "yarn build && yarn start"]

  node:
    build:
      context: .
      dockerfile: node.dockerfile
    working_dir: /srv/web
    volumes:
      - ./src:/srv/web
      - ${HOME}/.npm:${HOME}/.npm
      - ${HOME}/.npm-global:${HOME}/.npm-global